# Generated by Django 5.1.4 on 2025-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango_export_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangoexport',
            name='id',
        ),
        migrations.AlterField(
            model_name='mangoexport',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
